-- Commit 2: Lógica de negócio (PL/SQL)
CREATE OR REPLACE PROCEDURE PRC_FECHAR_ATENDIMENTO (p_id IN NUMBER) IS
BEGIN
    UPDATE TB_ATENDIMENTO 
    SET DS_SINTOMAS = DS_SINTOMAS || ' - FINALIZADO'
    WHERE ID_ATENDIMENTO = p_id;
    COMMIT;
END;
