-- Commit 1: Estrutura principal
CREATE TABLE TB_ATENDIMENTO (
    ID_ATENDIMENTO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PACIENTE NUMBER NOT NULL,
    DS_SINTOMAS VARCHAR2(500),
    DT_ENTRADA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
